title: International Planning Competition 2023 Classical Tracks
description: IPC 2023 Classical Tracks
theme: jekyll-theme-leap-day
show_downloads: false
markdown: GFM
github:
  is_project_page: false
